### ISSUE TITLE
Docker compose

### ISSUE THREAD

**Issue by mehransattary** [mehransattary/LearnDocker#4]
create docker-compose.yml in soluation

```
version: '3.7'

networks:
  mynet:

volumes:
  ApplicationSql:

services:
  application:
    container_name: project-container
    build:
      context: .
      dockerfile: MvcDocker/Dockerfile
    ports:
      - "5080:8080"
    networks:
      - mynet

  sql-server:
    container_name: SqlServer2022
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1533:1433
    networks:
      - mynet
    volumes:
      - ApplicationSql:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Strong2@PWD12
```

Create Dokcerfile 👍 

```
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["MvcDocker/MvcDocker.csproj", "MvcDocker/"]
RUN dotnet restore "./MvcDocker/MvcDocker.csproj"
COPY . .
WORKDIR "/src/MvcDocker"
RUN dotnet build "./MvcDocker.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./MvcDocker.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MvcDocker.dll"]
```
In terminal 👍  

`docker-compose up`
